name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from Dockerfile
        id: vars
        run: |
          FROM_LINE=$(grep '^FROM' Dockerfile)
          VERSION=$(echo "$FROM_LINE" | sed -E 's/.*:([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          MINOR_TAG=$(echo "$VERSION" | awk -F. '{print $1"."$2}')
          echo "full=$VERSION" >> $GITHUB_OUTPUT
          echo "minor=$MINOR_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sidroberts/php:${{ steps.vars.outputs.minor }}
            sidroberts/php:${{ steps.vars.outputs.full }}
